### ISSUE TITLE
[Bug] Weird scrolling behavior that freezes the UI

### ISSUE THREAD

**Issue by manucheri** [dangwu/Octal#83]
I sent in a review for this app on App Store, where I wrote that I liked the app but had problems with the UI freezing. Got an answer that told me to provide more details. So here it comes.

The issue happens quite often, but not all the time. It's a little tricky to reproduce but I just use the app like normal, and sometimes when I scroll in the comments the "scrolling" happens on one of the sub-threads/comments instead of the top level table view. And as soon as I let go of my finger (stop the touch events) the app stops responding. I cannot scroll or navigate anywhere, and my only solution is to force-quit the app.

So the app actually doesn't crash, it just stops reacting to touch events.

See video link: https://send.firefox.com/download/eaa2777bd4ae8116/#a25HzT7M6wlvvgRG7fecgQ

The bug happens at around 7 seconds in. You can see me scrolling, and then a period where nothing seems to happen (that is me trying to scroll/navigate but the app is not responding).

**Comment by dangwu** [comment]
Wow, this is crazy! I’ve never seen this before. Is there anything special
about your device or accessibility settings? Thanks so much for the report.

**Comment by manucheri** [comment]
iPhone X, iOS 12.3.1.
Swedish language, but other than that everything should be ”default”. No accessibility things turned on.

It is only this app that I have problems with. I have tried to see if there is something specific that triggers it, but no luck - it happens quite randomly when scrolling and interacting with comments.

**Comment by luckman212** [comment]
Thanks for reporting this. I've been experiencing this too since about 2 or 3 updates ago. Been collecting screenshots and trying to piece together repro steps but as of yet haven't nailed down exactly what causes it. 

I _think_ what may be happening is that the app is refreshing the comments in the background while you are scrolling in an "active" story ... and so someone posts a comment that changes the comment tree, somehow that is corrupting the view or the index.

iPhoneXS, iOS 12.3.1

**Comment by dangwu** [comment]
Thank you both for your efforts. I haven't been able to reproduce it myself yet. Using an iPhone X/Xs simulator and Xs physical device. I even tried using the "H.264 is magic (2016) thread from the video. I *do* remember this happening to me once, months ago, when developing/testing on a simulator.

**Comment by dangwu** [comment]
Let me know if you experience this issue in 3.6.0. It's built with a new version of Xcode and updated dependencies. I haven't seen the issue in weeks, using the app heavily.

**Comment by manucheri** [comment]
It still happens for me unfortunately. It seems to have gotten better though (only happened twice since the update), but might just be a coincidence.

It’s weird that you don’t experience these issues yourself. I will try to uninstall and reinstall the app and see if that changes anything.

**Comment by dangwu** [comment]
When the bug happens, can you swipe back to exit the comments view? Or do you have to just force quit the app?

**Comment by mikeknoop** [comment]
I think I’m affected by this same bug — started 3 or so updates ago. The UI locks up occasionally when scrolling comments. One comment gets  stuck in a “css position fixed” like way and after the current scrolling momentum stops, the entire app locks up. The only way out is to force close the app.

**Comment by manucheri** [comment]
@dangwu I cannot swipe back or navigate in any other way. The touch events seem completely lost (but the app doesn’t crash). I have to force quit the app completely to be able to use it again.

**Comment by dangwu** [comment]
Thanks for the reports! I honestly cannot reproduce this myself. My guess
is it’s some sort of threading/race condition. I’ll work on cleaning up and
refactoring the comments code for the next update.

**Comment by dangwu** [comment]
Hi all! Please update to 3.6.2 and see if the issue persists. I fixed a threading issue within the comments view that could’ve caused this freezing. Fingers crossed!

**Comment by manucheri** [comment]
It just happened again unfortunately. It had been working fine for 3 days, but today it happened. Still no better reproduction steps than "use app like normal and scroll in comments".

Version 3.6.2, iOS 12.3.1.

**Comment by luckman212** [comment]
Just happened again to me too, v3.6.2 + iOS 12.3.1

This was the thread I was reading if it makes any difference:
https://news.ycombinator.com/item?id=20137475

Something is definitely going on here- because I even force-quit the app and then went back into that thread and got it to freeze again...

**Comment by dangwu** [comment]
Ugh, sad. Thanks for the reports. It did happen to me once today but
there’s no stack trace or anything because the app doesn’t actually crash.
I’ll continue efforts to fix this for 2.6.3.

**Comment by dangwu** [comment]
2.6.3 is out and if nothing else, comments should load noticeably faster.
Please let me know if you reproduce the freezing! I fixed another threading
issue that could be the root cause but I’m kind of blindly throwing darts
at this point. Thanks!

**Comment by luckman212** [comment]
Just want to say THANK YOU :pray: for your efforts on this, it seems like a very tough bug (maybe just a bug in iOS framework).

**Comment by dangwu** [comment]
I appreciate it, Luke!

**Comment by dangwu** [comment]
Fingers crossed... has this happened to anyone recently? Hasn’t happened to me for over a week - since v3.6.3

**Comment by luckman212** [comment]
Sad to say but yes it happens to me quite often... happened as recently as yesterday (before the 3.8.0 was downloaded)

Still don't have a reliable way to reproduce but it seems to be some combination of

- app hasn't been force-quit for a while
- I'm browsing comments for a trending story that has people actively posting comments, so that one might be inserted "livel while you're in that view
- I intentionally or accidentally force-touch on a comment for a split second, invoking that blur action

Lately that seems to be the most reliable way I can get this crash/infinite loop or whatever it is to occur.

**Comment by luckman212** [comment]
*Update:* just happened to me in 3.8.0

This was the page:
https://news.ycombinator.com/item?id=20261668

**Comment by dangwu** [comment]
Thanks @luckman212. Those are definitely the factors I've seen myself.

**Comment by dangwu** [comment]
v3.8.2 is out and removes the 3D touch on comments. I have a strong feeling this issue was related to 3D touch. Let me know if it's fixed!

**Comment by luckman212** [comment]
Thanks for your continued efforts to squash this one! So far so good on 3.8.2 and I don't miss 3D touch on comments at all (I was always accidentally activating it anyway)

**Comment by manucheri** [comment]
3.8.2 has worked very well so far. Not a single issue yet.

**Comment by dangwu** [comment]
Perfect!
